4Ailen/backend

src/main/java/com/aliens/friendship/dto/ApplicantInfo.java
src/main/java/com/aliens/friendship/dto/MatchedApplicants.java
src/test/java/com/aliens/friendship/matching/MatchingTest.java

구현
1. 신청자 정보 받기
2. 질문 기반 필터링 후 언어 기반 필터링
3. 팀 매칭

#2 매칭 알고리즘 테스트구현

---

src/main/java/com/aliens/friendship/controller/ApiError.java
src/main/java/com/aliens/friendship/controller/ApiRes.java
src/main/java/com/aliens/friendship/controller/GlobalExceptionHandler.java

- ApiError 추가
- ApiRes 추가
- GlobalExceptionHandler 추가
resolves: #8

feat: response 관련 클래스 추가

---

build.gradle

- 저희 조금 더 안정적인 버전으로 바꾸도록 하죠!
- 스프링 버전 3.0.1 => 2.7.7 수정
- 자바 버전 17 => 11 수정
- 항상 감사합니다! 🙇‍♂️

chore: 빌드 버전 수정

---

build.gradle

자바 버전을 17로 변경함
resolves: #31
-  #31 
- 자바 버전을 변경하였습니다!
- 항상 감사합니다 코드에 이상 있으시면 의견 부탁드리겠습니다.

Chore: 자바 버전 변경

---

.gitignore
build.gradle
src/main/java/com/aliens/friendship/config/security/CustomUserDetailService.java
src/main/java/com/aliens/friendship/config/security/CustomUserDetails.java
src/main/java/com/aliens/friendship/config/security/SecurityConfig.java
src/main/java/com/aliens/friendship/controller/MatchingController.java
src/main/java/com/aliens/friendship/domain/Member.java
src/main/java/com/aliens/friendship/domain/Question.java
src/main/java/com/aliens/friendship/dto/ApplicantInfo.java
src/main/java/com/aliens/friendship/dto/MatchedApplicants.java
src/main/java/com/aliens/friendship/repository/MemberRepository.java
src/main/java/com/aliens/friendship/repository/QuestionRepository.java
src/main/java/com/aliens/friendship/service/MatchingService.java
src/main/java/com/aliens/friendship/service/MemberService.java
src/test/java/com/aliens/friendship/matching/MatchingTest.java

- Resolved #26
- API doc 기반으로 매칭 컨트롤러 코드 추가
- 매칭 서비스 코드 추가
- 리포지토리 코드 추가
- jwt는 제외하고 매칭만 구현했습니다!
- db에 임의로 데이터 넣어서 포스트맨으로 실행하여 확인했습니다!
- 팀 매칭하는 로직은 우선 /matching/result 호출 시 실행되도록 해뒀는데 나중에 특정 날짜가 되면 실행되도록 해야할까요?

Feature/#26 매칭 관련 코드

---

src/main/java/com/aliens/friendship/emailAuthentication/domain/EmailAuthentication.java

- #55 
- DB에는 다음과 같이 컬럼 생성했습니다
- EmailAuthentication 엔티티 클래스에 추가된 상태값 반영했습니다
- ERD 문서도 언제 한번 수정해야할 듯 하네요..?

feat/#55_entity EmailAuthentication 상태값 추가

---

src/main/java/com/aliens/friendship/chatting/domain/ChattingRoom.java
src/main/java/com/aliens/friendship/emailAuthentication/domain/EmailAuthentication.java
src/main/java/com/aliens/friendship/matching/domain/MatchingParticipant.java
src/main/java/com/aliens/friendship/matching/domain/Question.java
src/main/java/com/aliens/friendship/matching/service/MatchingService.java
src/main/java/com/aliens/friendship/member/domain/Member.java

- #37 
- 빌더 사용시 null값이 들어가지 않도록 디폴트 값 설정

refactor/#37 builder default값 설정

---

src/main/java/com/aliens/friendship/member/controller/APIController.java

- Resolved #79
- MemberService의 getMemberInfo 함수 수정에 따라 APIController의 getMemberInfo 수정
-

fix: APIController의 getMemberInfo 함수 수정

---

.gitignore
build.gradle
src/main/java/com/aliens/friendship/emailAuthentication/controller/EmailAuthenticationController.java
src/main/java/com/aliens/friendship/emailAuthentication/domain/EmailAuthentication.java
src/main/java/com/aliens/friendship/emailAuthentication/repository/EmailAuthenticationRepository.java
src/main/java/com/aliens/friendship/emailAuthentication/service/EmailAuthenticationService.java
src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java
src/main/java/com/aliens/friendship/member/repository/MemberRepository.java
src/main/resources/application.properties
src/main/resources/application.yml
src/test/java/com/aliens/friendship/emailAuthentication/controller/EmailAuthenticationControllerTest.java
src/test/java/com/aliens/friendship/emailAuthentication/service/EmailAuthenticationServiceTest.java

- Resolved #68
1. 이메일 인증 컨트롤러
- 코드 작성
- 테스트 케이스 작성
2. 이메일 인증 서비스
- 코드 작성
- 테스트 케이스 작성
3. properties 파일 yml으로 변경
- 우선 제 구글 계정으로 이메일 전송이랑 인증 확인했습니다!

feat/#68 이메일 인증 SMTP 구현

---

src/main/java/com/aliens/friendship/global/config/security/CustomUserDetails.java
src/main/java/com/aliens/friendship/member/controller/APIController.java
src/main/resources/application.yml
src/test/java/com/aliens/friendship/jwt/JwtAPITest.java
src/test/java/com/aliens/friendship/jwt/JwtUtilTest.java

- Resolved #95 
- 머지 이후 삭제된 CustomUserDetails의 role 설정 코드 추가
- 머지 이후 삭제된 APIController의 "/health" 추가
- jwt 관련 테스트 코드 실행 시 발생하는 오류 해결
- 이미 사용중인 이메일 변경
- 멤버 생성 시 이미지 설정 코드 추가
- jwt 비밀키 값 길이 연장
- 테스트 코드 실행 모두 확인했습니다  :)

fix/#95 jwt 관련 코드 수정

---

src/main/java/com/aliens/friendship/global/config/security/CustomUserDetails.java
src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java
src/main/java/com/aliens/friendship/matching/controller/MatchingController.java
src/main/java/com/aliens/friendship/matching/domain/BlockingInfo.java
src/main/java/com/aliens/friendship/matching/repository/BlockingInfoRepository.java
src/main/java/com/aliens/friendship/matching/service/BlockingInfoService.java
src/test/java/com/aliens/friendship/jwt/JwtAPITest.java
src/test/java/com/aliens/friendship/jwt/JwtUtilTest.java
src/test/java/com/aliens/friendship/matching/controller/MatchingControllerTest.java
src/test/java/com/aliens/friendship/matching/service/BlockingServiceTest.java

- 차단 기능 구현#86
- 컨트롤러 테스트 코드 추가
- 서비스 테스트 코드 추가
- BlockingInfo 의 컬럼 설정을 수정 (lazy -> eagar) 
- jwt 인증인가에서 role 관련 코드 추가 
- Mockito가 아직 친근하지 못합니다... 제가 조금 더 알아보고 수정하도록 하겠습니다.. 
+사용하는데 잘모르고 쓰고싶진 않아서 계속 더 알아보고 있습니다!

Feat/#86 block 차단기능 구현

---

src/main/java/com/aliens/friendship/domain/matching/domain/Report.java

- 신고 카테고리에 @Size 어노테이션이 제대로 적용되지 않는 문제 확인
- 신고 엔티티 reportCategory에 @Size 어노테이션 삭제

Hotfix 신고 엔티티 수정

---

src/main/java/com/aliens/friendship/domain/member/service/MemberService.java

- #133 
- yml등록된 파일 서버용 도메인 value로 domainUrl 수정
- 프로필 이미지 반환 코드 내 경로 수정
- 아파치 서버도 url 및 디렉토리 권한 설정 해두었습니다
- 관련해서 다른 이슈 있으면 언제든 말씀해주세요~

fix: 파일 경로 반환값 수정

---

src/main/java/com/aliens/friendship/domain/matching/controller/MatchingController.java
src/main/java/com/aliens/friendship/domain/matching/controller/dto/ReportResponse.java
src/main/java/com/aliens/friendship/domain/matching/domain/Report.java
src/main/java/com/aliens/friendship/domain/matching/service/ReportService.java
src/main/java/com/aliens/friendship/domain/member/controller/MemberController.java
src/main/java/com/aliens/friendship/domain/member/controller/dto/MemberInfoByAdminDto.java
src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java
src/test/java/com/aliens/friendship/emailAuthentication/service/EmailAuthenticationServiceTest.java
src/test/java/com/aliens/friendship/matching/controller/ServiceModelMatchingControllerTest.java
src/test/java/com/aliens/friendship/matching/service/ReportServiceTest.java
src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java
src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java

- Resolved #156 
- 기능 구현 및 관리자 권한 추가
- 멤버 삭제 및 조회
- 신고 목록 조회
- 매칭 로직
- 데이터베이스 변경 사항
- 신고 테이블에 신고 일시 속성 추가
- 테스트 코드 작성 
- 관리자 계정 제 이메일로 우선 만들었는데, 다음에 에이든님 이메일 인증 한번 부탁드리겠습니다!

feat/#156 관리자 권한 기능 구현

---

src/main/java/com/aliens/friendship/domain/matching/controller/MatchingController.java
src/main/java/com/aliens/friendship/domain/matching/service/MatchingInfoService.java
src/test/java/com/aliens/friendship/matching/controller/ServiceModelMatchingControllerTest.java
src/test/java/com/aliens/friendship/matching/service/ServiceModelMatchingInfoServiceTest.java

- Resolved #158 
- 매칭 남은 시간을 매칭 완료 일시로 반환하도록 코드 수정

refactor/#158 매칭 완료 일시 반환 API

---

src/main/java/com/aliens/friendship/domain/matching/controller/MatchingController.java
src/main/java/com/aliens/friendship/domain/member/controller/MemberController.java
src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java

fix: 반환값 오류 해결

---

membership/src/main/java/com/aliens/friendship/domain/member/exception/IdenticalPasswordException.java
membership/src/main/java/com/aliens/friendship/domain/member/exception/MemberExceptionCode.java
membership/src/main/java/com/aliens/friendship/domain/member/exception/MemberExceptionHandler.java
membership/src/main/java/com/aliens/friendship/domain/member/service/MemberService.java

- Resolved #188 
- 현재 비밀번호와 새 비밀번호가 동일하면 발생하는 예외 상황 추가
-

fix: 회원 비밀번호 변경 예외 추가 및 적용

---

membership/src/main/java/com/aliens/friendship/domain/emailauthentication/service/EmailAuthenticationService.java
membership/src/main/java/com/aliens/friendship/domain/member/service/MemberService.java

- Resolved #190 
- 한국어로 지원해주던 메일 내용을 영어와 한국어 함께 지원하도록 메일 내용 수정하였습니다. 
-

refactor : 한국어,영어 지원해주는 안내문으로 메일 내용 변경

---

membership/src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java

#192
- #192 
- 기존 서버에서 열려있더 ㄴswagger를 admin 계정만 접글할 수 있도록 config 수정 
-

refactor : swagger admin만 접근할 수 있돌고 막음

---

membership/src/main/java/com/aliens/friendship/domain/article/controller/ArticleController.java
membership/src/main/java/com/aliens/friendship/domain/article/service/ArticleService.java

- Resolved #218 
- 내가 작성한 댓글을 포함한 전체 게시글 조회,
- 내가 작성한 전체 게시글 조회,
- 전체 게시판 조회
pageimpl 적용 전, 각 results 리스트에 createdAt 기준 내림차순 정렬 적용해서 API 요청시 내림차순으로 제공하게 수정하였습니다. 
-

refactor : 전체 게시글 조회시 DESC 적용 

---

db/src/main/java/com/aliens/db/marketarticle/entity/MarketArticleEntity.java
membership/src/main/java/com/aliens/friendship/domain/article/market/dto/CreateMarketArticleRequest.java
membership/src/main/java/com/aliens/friendship/domain/article/market/dto/MarketArticleDto.java
membership/src/main/java/com/aliens/friendship/domain/article/market/dto/UpdateMarketArticleRequest.java
membership/src/main/java/com/aliens/friendship/domain/article/market/service/MarketArticleService.java

- Resolved #220 
- 장터게시판 stataus 변수명을 marketArticleStatus로 변경
-

refactor: 장터게시판 상태명 변경

---

membership/src/main/java/com/aliens/friendship/domain/article/community/service/CommunityArticleService.java
membership/src/main/java/com/aliens/friendship/domain/article/dto/ArticleDto.java
membership/src/main/java/com/aliens/friendship/domain/article/service/ArticleService.java

- Resolved #222 
- Resolved #224 
- 일반게시판 게시글 생성 및 수정 시 이미지가 없는 경우 오류가 발생하여 코드 수정
- 내가 댓글 쓴 게시글 전체 조회 시 게시글 중복 조회가 발생하여 코드 수정
-

Refactor, Fix: 일반게시판 이미지 없는 경우, 게시글 중복 조회 문제 해결

---

membership/build.gradle
membership/src/main/java/com/aliens/friendship/domain/match/business/MatchBusiness.java
membership/src/main/java/com/aliens/friendship/global/rabbitMQ/MatchCompletionProducer.java

- #225
- 매칭 완료시 메시지큐 비동기 통신으로 채팅서버에 알림을 보냅니다.
-

Feat/#225 rabbitmq 적용

---

db/src/main/java/com/aliens/db/communityarticle/entity/CommunityArticleEntity.java
db/src/main/java/com/aliens/db/marketarticle/entity/MarketArticleEntity.java

- Resolved #229 
- 게시글 삭제 시 연관된 하위 엔티티들 함께 삭제하도록 수정
-

fix: 게시글 삭제 오류 해결

---

membership/src/main/java/com/aliens/friendship/domain/applicant/converter/ApplicantConverter.java
membership/src/main/java/com/aliens/friendship/domain/personalNotice/service/PersonalNoticeService.java

- Resolved #237 
- 이미지 반환 시에 url로 반환이 이루어지도록 수정
-

fix: 이미지 반환 시 url로 반환되도록 수정
